const productData = [
  {
    id: 1,
    name: "Brush",
    category: "Grocery",
    sellingPrice: 30,
    buyingPrice: 25,
    quantityAvailable: 20,
    description: "Cleaning tool",
  },
  {
    id: 2,
    name: "Notebook",
    category: "Stationery",
    sellingPrice: 10,
    buyingPrice: 8,
    quantityAvailable: 50,
    description: "Writing pad",
  },
  {
    id: 3,
    name: "Headphones",
    category: "Electronics",
    sellingPrice: 50,
    buyingPrice: 40,
    quantityAvailable: 15,
    description: "Audio devices",
  },
  {
    id: 4,
    name: "Shampoo",
    category: "Grocery",
    sellingPrice: 15,
    buyingPrice: 12,
    quantityAvailable: 25,
    description: "Hair care",
  },
  {
    id: 5,
    name: "Pen Set",
    category: "Stationery",
    sellingPrice: 8,
    buyingPrice: 6,
    quantityAvailable: 30,
    description: "Writing tools",
  },
  {
    id: 6,
    name: "Laptop",
    category: "Electronics",
    sellingPrice: 800,
    buyingPrice: 700,
    quantityAvailable: 10,
    description: "Portable computer",
  },
  {
    id: 7,
    name: "Bread",
    category: "Grocery",
    sellingPrice: 2,
    buyingPrice: 1.5,
    quantityAvailable: 100,
    description: "Bakery item",
  },
  {
    id: 8,
    name: "Eraser",
    category: "Stationery",
    sellingPrice: 1,
    buyingPrice: 0.8,
    quantityAvailable: 50,
    description: "Correction tool",
  },
  {
    id: 9,
    name: "Smartphone",
    category: "Electronics",
    sellingPrice: 400,
    buyingPrice: 350,
    quantityAvailable: 20,
    description: "Mobile device",
  },
  {
    id: 10,
    name: "Milk",
    category: "Grocery",
    sellingPrice: 3,
    buyingPrice: 2,
    quantityAvailable: 30,
    description: "Dairy product",
  },
];

export default productData;
